// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navigation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-white dark:bg-neutral-900 border-b border-neutral-200 dark:border-neutral-700 shadow-sm sticky top-0 z-50 transition-colors duration-300\"><div class=\"flex justify-center items-center max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\" id=\"navbar-sticky\"><ul class=\"flex justify-center space-x-8 py-4 bg-gradient-to-r from-transparent via-white dark:via-neutral-800 to-transparent\"><li><a href=\"/\" class=\"text-neutral-900 dark:text-neutral-300 hover:text-blue-600 dark:hover:text-indigo-400 px-3 py-2 text-sm font-medium transition-colors rounded-md\">Home</a></li><li><a href=\"/wiki\" class=\"bg-gradient-to-r from-indigo-500 to-purple-600 bg-clip-text text-transparent dark:from-indigo-400 dark:to-purple-500 px-3 py-2 text-sm font-semibold transition-colors rounded-md border-b-2 border-indigo-500 dark:border-indigo-400\" aria-current=\"page\">Wiki</a></li><li><a href=\"/search\" class=\"text-neutral-900 dark:text-neutral-300 hover:text-blue-600 dark:hover:text-indigo-400 px-3 py-2 text-sm font-medium transition-colors rounded-md\">Search</a></li></ul></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
